# Generated by Django 3.1.1 on 2021-04-28 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationsBroadcast',
            fields=[
                ('broadcast_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('broadcast_name', models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotificationsBroadcast',
            fields=[
                ('user_broadcast_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationsbroadcast')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
