# Generated by Django 4.2.20 on 2025-09-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usernotificationsbroadcast',
            index=models.Index(fields=['user', 'broadcast'], name='user_broadcast_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotificationsbroadcast',
            index=models.Index(fields=['user'], name='user_idx'),
        ),
    ]
