# Generated by Django 4.0.4 on 2023-05-24 16:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('docmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
