# Generated by Django 4.0.4 on 2023-05-24 16:39

from django.db import migrations
import uuid

def random_document_token(apps, schema_editor):
    # get all documents
    Document = apps.get_model('docmanager', 'Document')

    docs = Document.objects.all()

    for doc in docs:
        doc.token = uuid.uuid4()
        doc.save()

class Migration(migrations.Migration):

    dependencies = [
        ('docmanager', '0002_document_token'),
    ]

    operations = [
        migrations.RunPython(random_document_token),
    ]
