# Generated by Django 4.2.4 on 2024-01-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docmanager', '0003_auto_20230524_1639'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_id'], name='docmanager__documen_6d9774_idx'),
        ),
    ]
