# Generated by Django 4.2.16 on 2024-12-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docmanager', '0004_document_docmanager__documen_6d9774_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filepath',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
