# Generated by Django 5.2.1 on 2026-01-12 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0423_delete_userfollow'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('configured_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(blank=True, default='', max_length=50)),
                ('primary_color', models.CharField(default='#351DC2', max_length=7)),
                ('support_email', models.EmailField(blank=True, default='', max_length=254)),
                ('logo_path', models.CharField(blank=True, default='', max_length=255)),
                ('display_settings', models.JSONField(default=dict)),
                ('is_reseller', models.BooleanField(default=False)),
                ('self_hosted', models.BooleanField(default=True)),
                ('support_multiple_associations', models.BooleanField(default=False)),
                ('show_course_athletes', models.BooleanField(default=True)),
                ('show_minor_exemption', models.BooleanField(default=True)),
                ('show_tutorial', models.BooleanField(default=True)),
                ('google_client_id', models.CharField(blank=True, default='', max_length=255)),
                ('apple_client_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_public_key', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_secret_key', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_webhook_secret', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_pricing_table', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_client_portal', models.URLField(blank=True, default='')),
                ('meta_title', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('primary_association', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance_config', to='application.sportassociation')),
            ],
            options={
                'verbose_name': 'Instance Configuration',
                'verbose_name_plural': 'Instance Configuration',
            },
        ),
    ]
