# Generated by Django 5.2.1 on 2026-08-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceconfiguration',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instanceconfiguration',
            name='setup_provenance',
            field=models.CharField(choices=[('fresh', 'Fresh setup'), ('import', 'Imported backup'), ('legacy', 'Legacy setup')], default='legacy', max_length=16),
        ),
    ]
