# Generated by Django 5.2.17 on 2026-09-23 17:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0004_instance_integrations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRestore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('association_id', models.UUIDField()),
                ('state', models.CharField(default='review', max_length=16)),
                ('stage', models.CharField(default='validated', max_length=32)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload_path', models.TextField(default='')),
                ('sha256', models.CharField(max_length=64)),
                ('version', models.CharField(default='', max_length=100)),
                ('preview', models.JSONField(default=dict)),
                ('backup_path', models.TextField(default='')),
                ('backup_sha256', models.CharField(default='', max_length=64)),
                ('media', models.JSONField(default=dict)),
                ('error', models.TextField(default='')),
                ('allow_missing_media', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('state__in', ['queued', 'running'])), fields=('association_id',), name='one_active_data_restore')],
            },
        ),
    ]
