# Generated by Django 5.2.1 on 2026-09-24 23:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0006_datarestoreuserdetachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BakneyLogin',
            fields=[
                ('digest', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('pairing_id', models.UUIDField()),
                ('state', models.CharField(max_length=64)),
                ('verifier_encrypted', models.TextField(default='')),
                ('stage', models.CharField(default='started', max_length=16)),
                ('user_id', models.UUIDField(null=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BakneyNonce',
            fields=[
                ('digest', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BakneyRevocation',
            fields=[
                ('pairing_id', models.UUIDField(primary_key=True, serialize=False)),
                ('authority', models.URLField()),
                ('secret_encrypted', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BakneyPairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pairing_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('secret_encrypted', models.TextField(default='')),
                ('authority', models.URLField(default='')),
                ('origin', models.URLField(default='')),
                ('association_id', models.UUIDField(null=True)),
                ('association_name', models.CharField(default='', max_length=255)),
                ('state', models.CharField(default='disconnected', max_length=16)),
                ('forwarding_enabled', models.BooleanField(default=False)),
                ('remote_revision', models.PositiveBigIntegerField(default=0)),
                ('checked_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='instance.instanceconfiguration')),
            ],
        ),
    ]
