# Generated by Django 5.2.1 on 2026-09-25 06:23

from django.db import migrations, models


def invalidate_previous_protocol(apps, schema_editor):
    # PR #15 originally used an incompatible draft protocol. Preserve the stable
    # instance ID, but never reuse its credentials or transactions after alignment.
    apps.get_model('instance', 'BakneyPairing').objects.update(
        state='disconnected', secret_encrypted='', authority='', association_name='',
        forwarding_enabled=False, checked_at=None)
    apps.get_model('instance', 'BakneyLogin').objects.all().delete()
    apps.get_model('instance', 'BakneyRevocation').objects.all().delete()
    apps.get_model('instance', 'BakneyNonce').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0007_bakneylogin_bakneynonce_bakneyrevocation_and_more'),
    ]

    operations = [
        migrations.RunPython(invalidate_previous_protocol, migrations.RunPython.noop),
        migrations.RemoveField(model_name='bakneypairing', name='remote_revision'),
        migrations.CreateModel(
            name='BakneyChallenge',
            fields=[
                ('digest', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('pairing_id', models.UUIDField()),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='bakneylogin',
            name='attempt_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='bakneylogin',
            name='remote_generation',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='bakneypairing',
            name='remote_generation',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='bakneypairing',
            name='remote_pairing_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='bakneypairing',
            name='ui_origin',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='bakneyrevocation',
            name='remote_pairing_id',
            field=models.UUIDField(null=True),
        ),
    ]
