# Generated by Django 4.2.20 on 2025-10-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial_squashed_0413_associate_associate_sport_assoc_id_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='signature_url',
            field=models.CharField(max_length=1024, null=True, blank=True, help_text='S3 URL for signature image'),
        ),
    ]
