# Generated by Django 4.2.20 on 2025-10-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0414_add_signature_url_to_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='signature',
        ),
    ]
