# Generated by Django 4.2.20 on 2025-10-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0415_remove_subscription_signature'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(condition=models.Q(('archived', False), ('deleted', False)), fields=['sport_association', 'payment_date'], name='active_payments_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['sport_association', 'paid', 'amount'], include=('payment_date', 'description'), name='payment_summary_idx'),
        ),
    ]
