# Generated by Django 4.2.20 on 2025-10-14 20:16
# Quick Win Optimization: Section 7.1 - Add Missing Indexes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0416_payment_active_payments_idx_and_more'),
    ]

    operations = [
        # Index for collaborator lookups (User.connected_user)
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['connected_user'], name='user_connected_idx')
        ),

        # Partial index for active subscriptions
        # This improves queries that filter by active/current subscriptions
        migrations.RunSQL(
            sql='''
            CREATE INDEX sub_active_idx ON application_subscription (sport_association_id, start_date, end_date)
            WHERE deleted = FALSE AND archived = FALSE;
            ''',
            reverse_sql='DROP INDEX IF EXISTS sub_active_idx;'
        ),

        # Index for soft delete filtering on Associate
        migrations.AddIndex(
            model_name='associate',
            index=models.Index(
                fields=['sport_association', 'deleted'],
                name='associate_deleted_idx'
            )
        ),

        # Index for Instructor lookups by user
        migrations.AddIndex(
            model_name='instructor',
            index=models.Index(
                fields=['user', 'draft'],
                name='instructor_user_draft_idx'
            )
        ),
    ]
