# Generated by Django 4.2.25 on 2025-10-14 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0417_add_quick_win_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='associate',
            name='application_sport_a_f36e4c_idx',
        ),
        migrations.AlterField(
            model_name='billingpayment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billingsubscription',
            name='billing_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='application.billingplan'),
        ),
        migrations.AlterField(
            model_name='billingsubscription',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nurturingemails',
            name='nurturing_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='application.nurturingemailsplan'),
        ),
        migrations.AlterField(
            model_name='nurturingemails',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payment_amount_positive'),
        ),
    ]
