# Generated by Django 4.2.25 on 2025-11-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0419_add_renewal_check_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportassociation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
