# Generated by Django 4.2.25 on 2026-01-06 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUDITLOG_LOGENTRY_MODEL),
        ('application', '0420_sportassociation_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogIndex',
            fields=[
                ('audit_log_index_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('resolution_path', models.CharField(blank=True, help_text="Path used to resolve sport_association (e.g., 'direct', 'course.sport_association')", max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('log_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sport_association_index', to=settings.AUDITLOG_LOGENTRY_MODEL)),
                ('sport_association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.sportassociation')),
            ],
            options={
                'verbose_name': 'Audit Log Index',
                'verbose_name_plural': 'Audit Log Indexes',
                'indexes': [models.Index(fields=['sport_association', 'created_at'], name='application_sport_a_da3d3f_idx'), models.Index(fields=['sport_association', 'log_entry'], name='application_sport_a_2eefdd_idx')],
            },
        ),
    ]
