# Generated by Django 5.2.1 on 2026-02-16 21:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0423_delete_userfollow'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('saved_report_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('tool_name', models.CharField(max_length=100)),
                ('params', models.JSONField(default=dict)),
                ('ui_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to=settings.AUTH_USER_MODEL)),
                ('sport_association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.sportassociation')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['sport_association', 'created_by'], name='application_sport_a_57ba7b_idx')],
            },
        ),
    ]
