"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
import logging
import base64
from urllib.parse import urlparse

import environ
from pathlib import Path
from datetime import timedelta
import stripe

# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent

# Environment
env = environ.Env()
base = environ.Path(BASE_DIR)
environ.Env.read_env(env_file=base('.env'))


def env_key(name):
    encoded = env.str(f'{name}_B64', '')
    if encoded:
        return base64.b64decode(encoded).decode('utf-8')
    return env.str(name, multiline=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str('SECRET_KEY')
JWT_SECRET_KEY = env_key('JWT_SECRET_KEY')
JWT_PUBLIC_KEY = env_key('JWT_PUBLIC_KEY')

APP_HOST = env.str('APP_HOST')
APP_URL = env.str('APP_URL', f'https://{APP_HOST}').rstrip('/')
INSTANCE_SETUP_TOKEN = env.str('INSTANCE_SETUP_TOKEN', '')


# STRIPE CONFIGURATION
STRIPE_KEY = env.str('STRIPE_KEY', '')
STRIPE_REFRESH_URL = env.str('STRIPE_REFRESH_URL', f'{APP_URL}/#/stripe/onboarding')
STRIPE_RETURN_URL = env.str('STRIPE_RETURN_URL', f'{APP_URL}/#/stripe/onboarded')
STRIPE_WEBHOOK_SECRET = env.str('STRIPE_WEBHOOK_SECRET')
DOCUMENT_BYPASS_TOKEN = env.str('DOCUMENT_BYPASS_TOKEN')
SENJA_WEBHOOK_SECRET = env.str('SENJA_WEBHOOK_SECRET')

# SET STRIPE KEY GLOBALLY
stripe.api_key = STRIPE_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG')

RATELIMIT_ENABLE = env.bool('RATELIMIT_ENABLE', not DEBUG)

# EMAIL SPAM FILTER
DEC_LOADER = "application.disposable_email.custom_email_domain_loader"

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1', 'api'])
CORS_ORIGIN_ALLOW_ALL = env.bool('CORS_ORIGIN_ALLOW_ALL', DEBUG)
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[])
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])

# Caddy terminates TLS and forwards the original scheme to Django.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', not DEBUG)

CURRENT_HOST = env.str('CURRENT_HOST')

# Read version from VERSION file (injected at build time), fallback to env var
def _get_running_version():
    version_file = BASE_DIR / 'VERSION'
    if version_file.exists():
        version = version_file.read_text().strip()
        if version:
            return version
    return env.str('RUNNING_VERSION', 'v0.0.0')

RUNNING_VERSION = _get_running_version()

# 250 MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 262144000

# WHITE LABEL & RESELLER SETTINGS
IS_WHITELABEL = env.bool('IS_WHITELABEL', False)
IS_RESELLER = env.bool('IS_RESELLER', False)
DEFAULT_SPORT_ASSOCIATION_ID = env.str('DEFAULT_SPORT_ASSOCIATION_ID', None)
WHITELABEL_NAME = env.str('WHITELABEL_NAME', 'Bakney Sport')
RESELLER_NAME = env.str('RESELLER_NAME', 'Bakney Sport')

# GROQ API KEY
GROQ_API_KEY = env.str('GROQ_API_KEY', None)
GROQ_MODEL = env.str('GROQ_MODEL', 'openai/gpt-oss-120b')
GROQ_CHEAP_MODEL = env.str('GROQ_CHEAP_MODEL', 'openai/gpt-oss-20b')
GROQ_BASE_URL = env.str('GROQ_BASE_URL', 'https://api.groq.com/openai/v1')

# MCP Agent Settings
MCP_AGENT_MAX_ITERATIONS = env.int('MCP_AGENT_MAX_ITERATIONS', 15)
MCP_AGENT_MAX_RESULTS = env.int('MCP_AGENT_MAX_RESULTS', 5000)
MCP_AGENT_QUERY_TIMEOUT = env.int('MCP_AGENT_QUERY_TIMEOUT', 10)
MCP_AGENT_WS_RATE_LIMIT = env.int('MCP_AGENT_WS_RATE_LIMIT', 10)
MCP_AGENT_WS_TIMEOUT = env.int('MCP_AGENT_WS_TIMEOUT', 240)
MCP_AGENT_HISTORY_CAP = env.int('MCP_AGENT_HISTORY_CAP', 50)

# Pdf Rendering ENGINE
PUPPETEER_HOST = env.str('PUPPETEER_HOST')
PUPPETEER_PORT = env.str('PUPPETEER_PORT')
CURRENT_HOST_PUPPETEER = env.str('CURRENT_HOST_PUPPETEER')

# REDIS DB
REDIS_HOST = os.environ.get("REDIS_HOST", 'localhost')
REDIS_PORT = os.environ.get("REDIS_PORT", 6379)
REDIS_USERNAME = os.environ.get("REDIS_USERNAME", 'default')
REDIS_PASSWORD = os.environ.get("REDIS_PASSWORD")
REDIS_SSLAUTH = os.environ.get("REDIS_SSLAUTH", False)
REDIS_SSLCERT = os.environ.get("REDIS_SSLCERT")

REDIS_PROTOCOL = 'redis' if not REDIS_SSLAUTH else 'rediss'

# CELERY CONFIGURATION
CELERY_BROKER_URL = f'{REDIS_PROTOCOL}://{REDIS_USERNAME}:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}'
# save Celery task results in Django's database
CELERY_RESULT_BACKEND = "django-db"
# this allows you to schedule items in the Django admin.
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'
# useful for mitigating memory leaks
CELERY_WORKER_MAX_TASKS_PER_CHILD = 100

# Redis cache configuration
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"{REDIS_PROTOCOL}://{REDIS_HOST}:{REDIS_PORT}/1",  # Using database 1 for cache
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": REDIS_PASSWORD,
        }
    }
}

# Session configuration (unchanged)
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# Additional Redis-specific settings
if REDIS_USERNAME and REDIS_USERNAME != 'default':
    CACHES['default']['OPTIONS']['USERNAME'] = REDIS_USERNAME

if REDIS_SSLAUTH:
    CACHES['default']['OPTIONS']['SSL'] = True
    if REDIS_SSLCERT:
        CACHES['default']['OPTIONS']['SSL_CERT_REQS'] = 'required'
        CACHES['default']['OPTIONS']['SSL_CA_CERTS'] = REDIS_SSLCERT


# # Database cache configuration
# CACHES = {
#     "default": {
#         "BACKEND": "django.core.cache.backends.db.DatabaseCache",
#         "LOCATION": "caching_table",
#     }
# }
#
# SESSION_ENGINE = "django.contrib.sessions.backends.cache"
# SESSION_CACHE_ALIAS = "default"

# clear cache on startup (TODO: refactor because it's bad practice)
# from django.core.cache import cache
# cache.clear()

# OAuth2 settings removed - migrated to JWT auth
# REPLICATE_API_TOKEN, TESSERACT_PATH, POPPLER_PATH removed - not used

# Custom Settings
ADMIN_URL = env.str('ADMIN_URL')

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.IsAuthenticated'
        'rest_framework.permissions.AllowAny'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    "DATE_INPUT_FORMATS": ['%d/%m/%Y'],
    "TEST_REQUEST_DEFAULT_FORMAT": "json",
}

# JWT Configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=4),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,  # No blacklist - using short expiry
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'EdDSA',
    'SIGNING_KEY': JWT_SECRET_KEY,
    'VERIFYING_KEY': JWT_PUBLIC_KEY,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'user_id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Bakney Sport API',
    'DESCRIPTION': 'Bakney Sport is a sport association platform that allows you to manage your sport association.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_DIST': 'SIDECAR',  # shorthand to use the sidecar instead
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
    # OTHER SETTINGS
}

AUTHENTICATION_BACKENDS = (
    # Social auth backends (for Google/Apple login verification)
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.apple.AppleIdAuth',
    'social_core.backends.orcid.ORCIDOAuth2',

    # Django default
    'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_JSONFIELD_ENABLED = True

# # Facebook configuration
# SOCIAL_AUTH_FACEBOOK_KEY = env.int('FACEBOOK_APP_ID')
# SOCIAL_AUTH_FACEBOOK_SECRET = env.str('FACEBOOK_SECRET_KEY')
#
# # Define SOCIAL_AUTH_FACEBOOK_SCOPE to get extra permissions from Facebook.
# # Email is not sent by default, to get it, you must request the email permission.
# SOCIAL_AUTH_FACEBOOK_SCOPE = ['id', 'email', 'picture', 'name']
# SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
#     'fields': 'id, name, email, picture'
# }
# SOCIAL_AUTH_FACEBOOK_API_VERSION = '15.0'

# Google configuration
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = env.str('SOCIAL_AUTH_GOOGLE_OAUTH2_KEY')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = env.str('SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET')

SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile',
    'openid',
]

# Apple configuration
# Your client_id com.application.your, aka "Service ID"
SOCIAL_AUTH_APPLE_ID_CLIENT = env.str('SOCIAL_AUTH_APPLE_ID_CLIENT', '')
# Your Team ID, ie K2232113
SOCIAL_AUTH_APPLE_ID_TEAM = env.str('SOCIAL_AUTH_APPLE_ID_TEAM', '')
# Your Key ID, ie Y2P99J3N81K
SOCIAL_AUTH_APPLE_ID_KEY = env.str('SOCIAL_AUTH_APPLE_ID_KEY', '')
SOCIAL_AUTH_APPLE_ID_SECRET = env.str('SOCIAL_AUTH_APPLE_ID_SECRET', '', multiline=True)

SOCIAL_AUTH_APPLE_ID_SCOPE = ['email', 'name']
SOCIAL_AUTH_APPLE_ID_EMAIL_AS_USERNAME = True   # If you want to use email as username

# email server settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Use in-memory backend during tests (no real emails sent)
import sys
if 'test' in sys.argv:
    EMAIL_BACKEND = 'django.core.mail.backends.locmem.EmailBackend'

EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_PORT = os.environ.get('EMAIL_PORT')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_SUPPORT = os.environ.get('EMAIL_HOST_SUPPORT')
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', False) #True
EMAIL_USE_SSL = env.bool('EMAIL_USE_SSL', True) #False
DEFAULT_FROM_EMAIL = f"{WHITELABEL_NAME} <{EMAIL_HOST_USER}>"
DEFAULT_SUPPORT_EMAIL = f"{WHITELABEL_NAME} <{EMAIL_HOST_SUPPORT}>"
DEFAULT_TEAM_EMAIL = f"Il Team di {WHITELABEL_NAME} <{EMAIL_HOST_USER}>"

# GOOGLE CALENDAR API
GOOGLE_CALENDAR_CLIENT_SECRET_FILE = os.environ.get('GOOGLE_CLIENT_SECRET_FILE', 'google_client_secret.json')
GOOGLE_CALENDAR_REDIRECT_URL = os.environ.get('GOOGLE_CALENDAR_REDIRECT_URL', f"{CURRENT_HOST}/google/oauth2callback")
GOOGLE_CALENDAR_SCOPES = [
    'https://www.googleapis.com/auth/calendar',
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile',
    'openid'
]
GOOGLE_CALENDAR_API_SERVICE_NAME = 'calendar'
GOOGLE_CALENDAR_API_VERSION = 'v3'

SMSAPI_TOKEN = os.environ.get('SMSAPI_TOKEN', None)

SMS_100_LINE_ITEM = os.environ.get('SMS_100_LINE_ITEM', None)
SMS_200_LINE_ITEM = os.environ.get('SMS_200_LINE_ITEM', None)
SMS_300_LINE_ITEM = os.environ.get('SMS_300_LINE_ITEM', None)

INSTALLED_APPS = [
    'corsheaders',
    'docmanager',
    'django_extensions',
    'application',
    'communications',
    'application.templatetags.format',
    'notifications',
    'instance',
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django',
    'rest_framework',
    'auditlog',
    'storages',
    'django_celery_beat',
    'django_celery_results',
    # 'social_django',
    # 'rest_framework_social_oauth2',
    'channels',
    'mptt',
    'drf_api_logger',
    'drf_spectacular',  # keep it last one
    'drf_spectacular_sidecar',
]

if DEBUG:
    INSTALLED_APPS += ['silk']

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',

    # Send a validation email to the user to verify its email address.
    # Disabled by default.
    # 'social_core.pipeline.mail.mail_validation',

    # Associates the current social details with another user account with
    # a similar email address. Disabled by default.
    'social_core.pipeline.social_auth.associate_by_email',

    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)

AUTH_USER_MODEL = 'application.User'

MIDDLEWARE = [
    'django.middleware.gzip.GZipMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    # "kolo.middleware.KoloMiddleware",
    'django.middleware.security.SecurityMiddleware',
    # OPTIMIZED: Use ConditionalSessionMiddleware instead of SessionMiddleware
    # This skips session loading for API requests (saves 3-8ms per request)
    # Sessions are still used for Django admin and web routes
    'core.middleware.ConditionalSessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.messages.middleware.MessageMiddleware',
    # OPTIMIZED: Commented out ClickjackingMiddleware - not needed for API routes (saves ~1-2ms)
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'social_django.middleware.SocialAuthExceptionMiddleware',
    # DO NOT REMOVE THIS MIDDLEWARE, it is going to break the application if not reading request.body in middleware
    # 'drf_api_logger.middleware.api_logger_middleware.APILoggerMiddleware',
    'core.middleware.ExceptionHandlerMiddleware',
    'auditlog.middleware.AuditlogMiddleware',  # Required for audit logging
    'application.mixin.GroupSelectionMiddleware',
]

if DEBUG:
    MIDDLEWARE += ['silk.middleware.SilkyMiddleware']

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = 'core.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [{"address": f"{REDIS_PROTOCOL}://{REDIS_HOST}:{REDIS_PORT}/0", "password": REDIS_PASSWORD}],
        },
    },
}

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
DBTYPE = os.environ.get('DBTYPE')
DBNAME = os.environ.get('DBNAME')
DBUSER = os.environ.get('DBUSER')
DBPASSWORD = os.environ.get('DBPASSWORD')
DBHOST = os.environ.get('DBHOST')
DBPORT = os.environ.get('DBPORT')
DBSSLMODE = os.environ.get('DBSSLMODE', None)
DBSSLROOTCERT = os.environ.get('DBSSLROOTCERT', None)
# os.path.join(BASE_DIR,
USE_PGBOUNCER = os.environ.get('USE_PGBOUNCER', 'False') == 'True'
PGBOUNCER_HOST = os.environ.get('PGBOUNCER_HOST', 'localhost')
PGBOUNCER_PORT = os.environ.get('PGBOUNCER_PORT', '6432')

if DBTYPE == "POSTGRES":
    if USE_PGBOUNCER:
        # When using PgBouncer in transaction mode
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': DBNAME,
                'USER': DBUSER,
                'PASSWORD': DBPASSWORD,
                'HOST': PGBOUNCER_HOST,  # Connect to PgBouncer
                'PORT': PGBOUNCER_PORT,  # PgBouncer port (6432)
                'DISABLE_SERVER_SIDE_CURSORS': True,  # Required for transaction mode
                'CONN_MAX_AGE': None,    # Let PgBouncer manage connection lifecycle
                'OPTIONS': {
                    'connect_timeout': 10,  # Timeout for new connections
                },
            }
        }
    else:
        # Direct database connection
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': DBNAME,
                'USER': DBUSER,
                'PASSWORD': DBPASSWORD,
                'HOST': DBHOST,
                'PORT': DBPORT,
                'CONN_MAX_AGE': 10,  # Keep connections for 10 seconds
            }
        }

    if DBSSLMODE and DBSSLROOTCERT:
        DATABASES['default']['OPTIONS'] = {
            'sslmode': DBSSLMODE,
            'sslrootcert': DBSSLROOTCERT,
        }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
            'TEST': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': os.path.join(BASE_DIR, 'test_db.sqlite3')
            },
            'OPTIONS': {
                'timeout': 20,
            }
        },
    }

# Celery adjustments for PgBouncer
if USE_PGBOUNCER:
    # Celery should use separate pool
    CELERY_DB_POOL_SIZE = 4
    CELERY_RESULT_BACKEND_POOL_SIZE = 4

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'it'
TIME_ZONE = 'UTC'
USE_I18N = True
# USE_L10N removed - deprecated in Django 4.0, removed in Django 5.0 (localization always enabled)
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Application definition
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# LOGGING
class CustomFormatter(logging.Formatter):
    """Custom formatter to include extra fields dynamically"""
    def format(self, record):
        # Extract extra fields (anything not in default LogRecord)
        default_attrs = {
            'name', 'msg', 'args', 'created', 'filename', 'funcName', 'levelname',
            'levelno', 'lineno', 'module', 'msecs', 'message', 'pathname', 'process',
            'processName', 'relativeCreated', 'thread', 'threadName', 'exc_info',
            'exc_text', 'stack_info', 'asctime'
        }
        extra_fields = {k: v for k, v in record.__dict__.items() if k not in default_attrs}

        # Rename logger names
        if record.name == 'root':
            record.name = 'API'
        elif record.name.startswith('django.server'):
            record.name = 'SERVER'
        elif record.name.startswith('django'):
            record.name = 'DJANGO'
        elif record.name.startswith('application'):
            record.name = 'API'

        # Format base message
        base_msg = super().format(record)

        # Append extra fields if any
        if extra_fields:
            extra_str = ' | ' + ' '.join(f'{k}={v}' for k, v in extra_fields.items())
            return base_msg + extra_str
        return base_msg

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            '()': 'core.settings.CustomFormatter',
            'format': '{asctime} [{levelname}] <{name}> -> {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django.server': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'application': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'core/static'),
)

DEFAULT_AUTO_FIELD='django.db.models.AutoField'

# DOCUMENT STORAGE DIR
STORE_ON_DISK = env.bool('STORE_ON_DISK', False)

# STORAGE DIR
STORAGE_DIR = os.path.join(BASE_DIR, env.str('STORAGE_DIR', 'storage'))

# AWS S3 CONFIGURATION
AWS_ACCESS_KEY_ID = env.str('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = env.str('AWS_SECRET_ACCESS_KEY')

AWS_STORAGE_BUCKET_NAME = env.str('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = env.str('AWS_S3_REGION_NAME')
AWS_S3_ENDPOINT_URL = env.str('AWS_S3_ENDPOINT_URL')


def _is_digitalocean_spaces_endpoint(endpoint_url):
    parsed = urlparse(endpoint_url if '://' in endpoint_url else f'//{endpoint_url}')
    hostname = (parsed.hostname or '').lower()
    return hostname == 'digitaloceanspaces.com' or hostname.endswith('.digitaloceanspaces.com')


AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
AWS_LOCATION = env.str('AWS_LOCATION')
AWS_DEFAULT_ACL = env.str('AWS_DEFAULT_ACL', None)
AWS_S3_FILE_OVERWRITE = env.bool('AWS_S3_FILE_OVERWRITE', False)
AWS_S3_USE_OBJECT_ACL = env.bool(
    'AWS_S3_USE_OBJECT_ACL',
    default=_is_digitalocean_spaces_endpoint(AWS_S3_ENDPOINT_URL)
)
_default_s3_public_base_url = ''
if _is_digitalocean_spaces_endpoint(AWS_S3_ENDPOINT_URL):
    _default_s3_public_base_url = (
        f'https://{AWS_STORAGE_BUCKET_NAME}.{AWS_S3_REGION_NAME}.digitaloceanspaces.com'
    )
AWS_S3_PUBLIC_BASE_URL = env.str(
    'AWS_S3_PUBLIC_BASE_URL',
    default=_default_s3_public_base_url
).rstrip('/')

STORAGE_DIR = ''    # f'https://{AWS_S3_ENDPOINT_URL}/{AWS_LOCATION}/'

# Django 5.0+ STORAGES configuration (replaces DEFAULT_FILE_STORAGE)
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# API LOGGER CONFIGURATION
DRF_API_LOGGER_DATABASE = True # log every request in the database
DRF_API_LOGGER_PATH_TYPE = 'ABSOLUTE'
# DRF API LOGGER takes anything < 0 as no limit.
# If response body > 1024 bytes, ignore.
#DRF_API_LOGGER_MAX_REQUEST_BODY_SIZE = 1024  # default to -1, no limit.
#DRF_API_LOGGER_MAX_RESPONSE_BODY_SIZE = 1024  # default to -1, no limit.
DRF_LOGGER_QUEUE_MAX_SIZE = 1 # Default to 50 if not specified.
DRF_LOGGER_INTERVAL = 1 # In Seconds, Default to 10 seconds if not specified.
DRF_API_LOGGER_SKIP_URL_NAME = ['', 'health']
DRF_API_LOGGER_SLOW_API_ABOVE = 300
DRF_API_LOGGER_METHODS = ['PATCH', 'POST', 'DELETE', 'PUT']


# CRM token API
CRM_API_TOKEN = env.str('CRM_API_TOKEN')
