// Real list selections, actual UI mutations and database rereads; no request mocking.
import {scenario,expect} from './scenario.mjs';
import {dashboardListsAuthoredWorkflows} from '../../../../docs/manuale/dashboard-lists-authored-workflows.mjs';
import {dashboardListsHarness} from './dashboard-lists-harness.mjs';
import {reloadOrganizationProfile} from './organization-access-sources.mjs';
const id='dashboard-lists',spec=dashboardListsAuthoredWorkflows[id];
await scenario({id,prefix:spec.prefix.replace(/\/$/,''),sources:spec.sources,
 actions:async({page,api,actor,input,capture,report})=>{
    expect(input.fixture_version).toBe(8);expect(input.fixture_profile||'baseline').toBe('baseline');
    const read=async(route,request=api)=>{const r=await request(route);expect(r.status()).toBe(200);return r.json();};
    const widget=async(name,key,request=api)=>(await read('statistic/dashboard?widget='+name,request)).data[key];
    const profile=()=>read('profile/info');
    const originalLayout=(await profile()).user_data.dashboard_layout;
    const originalSubscriptions=(await read('subscription/list?pagination[perpage]=100')).data;
    const originalPayments=(await read('payment/list?pagination[perpage]=100')).data;
    const layout={rows:[['todaylessons','expiringcarnets','subscriptionstoapprove','expiringmedicalcertificates',
        'expiredmedicalcertificates','expiredPayments'].map(id=>({id,size:12}))]};
    const applyLayout=async(request,value)=>{expect((await request('statistic/dashboard/layout',
        {method:'POST',data:{dashboard_layout:value}})).status()).toBe(200);};
    const f=dashboardListsHarness('prepare',input);let reader,readerLayout;
    const cards=(p,title)=>p.locator('.dashboard-widget').filter({has:p.locator('.card-label').filter({hasText:new RegExp('^'+title+'$')})});
    const card=title=>cards(page,title);
    const take=async(cp,focus,current=page)=>{
        const index=spec.checkpoints.findIndex(c=>c.id===cp);expect(index).toBeGreaterThanOrEqual(0);
        await expect(current.locator('[data-sonner-toast]:visible')).toHaveCount(0,{timeout:15000});
        await capture(current,index+1,cp,focus);
    };
    const postFor=(route,p=page)=>p.waitForResponse(r=>new URL(r.url()).pathname==='/api/'+route&&r.request().method()==='POST');
    const reloadDashboard=async(p=page,request=api)=>{await p.goto(input.origin+'/#/');
        await reloadOrganizationProfile({page:p,api:request,expect});
        await expect(cards(p,'Registro presenze lezioni')).toHaveCount(1);};
    const pendingItem=(p,key)=>cards(p,'Iscrizioni da approvare').locator('.border-right').filter({has:p.locator(`a[href$="/members/list/detail/${f.subscriptions[key].id}/info"]`)});
    const state=()=>dashboardListsHarness('inspect',input);
    const facts={};const proof=(key,value)=>{expect(value,key).toEqual(spec.outcome.expected[key]);facts[key]=value;};
    try {
        await applyLayout(api,layout);await reloadDashboard();
        const lessons=await widget('todaylessons','lessons');
        expect(lessons.map(x=>x.attendance_day_id)).toEqual([f.days.today]);
        expect(lessons[0].total_attendees).toBe(0);expect(lessons[0].total_expected_total).toBe(2);
        await expect(card('Registro presenze lezioni')).toContainText('0 / 2');
        await take('dashboard-list-today-lesson',card('Registro presenze lezioni'));
        await expect(card('Registro presenze lezioni').getByRole('button',{name:'Presenze',exact:true})).toBeEnabled();
        await card('Registro presenze lezioni').getByRole('button',{name:'Presenze',exact:true}).click();
        let modal=page.locator('#attendance-day-'+f.days.today);await expect(modal).toBeVisible();
        await expect(modal.locator('input[type="checkbox"]')).toHaveCount(2);await take('dashboard-list-attendance-editor',modal.locator('.modal-content'));
        const change=postFor(`course/${f.course_id}/attendees/${f.days.today}/update`);
        await modal.locator('.checkbox-list > div').filter({hasText:'Bianchi Giulia'}).locator('input[type="checkbox"]').locator('..').click();
        expect((await change).status()).toBe(200);await modal.getByText('Chiudi',{exact:true}).click();
        await reloadDashboard();expect(state().days.today).toEqual([{course_subscription_id:f.enrollment_ids[0]}]);
        await expect(card('Registro presenze lezioni')).toContainText('1 / 2');await take('dashboard-list-attendance-persists',card('Registro presenze lezioni'));
        proof('today_only_and_presence_persisted',true);
        reader=await actor('reader');readerLayout=(await read('profile/info',reader.api)).user_data.dashboard_layout;
        await applyLayout(reader.api,layout);await reloadDashboard(reader.page,reader.api);
        await cards(reader.page,'Registro presenze lezioni').getByRole('button',{name:'Presenze',exact:true}).click();
        const readerModal=reader.page.locator('#attendance-day-'+f.days.today);
        await expect(readerModal).toBeVisible();
        for(const box of await readerModal.locator('input[type="checkbox"]').all())await expect(box).toBeDisabled();
        const attendanceBefore=state().days;
        expect((await reader.api(`course/${f.course_id}/attendees/${f.days.today}/update`,{method:'POST',data:{attendees:[]}})).status()).toBe(403);
        expect(state().days).toEqual(attendanceBefore);await take('dashboard-list-reader-attendance-disabled',readerModal.locator('.modal-content'),reader.page);
        await readerModal.getByText('Chiudi',{exact:true}).click();proof('reader_attendance_denied_unchanged',true);
        const carnets=await widget('expiringcarnets','expiring_carnets');
        expect(carnets.map(x=>x.carnet_subscription_id).sort()).toEqual(['zero-recent','one','three'].map(key=>f.carnets[key].id).sort());
        for(const key of ['zero-recent','one','three'])await expect(card('Carnet in esaurimento').getByText(f.carnets[key].title,{exact:true})).toBeVisible();
        for(const key of ['zero-old','four'])await expect(card('Carnet in esaurimento').getByText(f.carnets[key].title,{exact:true})).toHaveCount(0);
        await take('dashboard-list-carnet-boundaries',card('Carnet in esaurimento'));
        await card('Carnet in esaurimento').locator(`a[href$="/members/list/detail/${input.subscription_ids[0]}/carnet"]`).first().click();
        await expect(page).toHaveURL(new RegExp('/members/list/detail/'+input.subscription_ids[0]+'/carnet'));
        await expect(page.locator('.card-title').filter({hasText:/Giulia/})).toContainText('Bianchi');
        await expect(page.locator('.card-label').filter({hasText:/Carnet/})).toBeVisible();
        await take('dashboard-list-carnet-member-link');await reloadDashboard();proof('carnet_zero_recent_one_three_only',true);
        const pending=await widget('subscriptionstoapprove','subscriptions_to_approve');
        expect(pending.map(x=>x.subscription_id).sort()).toEqual(['pending','unsigned'].map(k=>f.subscriptions[k].id).sort());
        await expect(card('Iscrizioni da approvare')).toContainText('in attesa');await expect(card('Iscrizioni da approvare')).toContainText('non firmata');
        await take('dashboard-list-pending-and-unsigned',card('Iscrizioni da approvare'));
        const beforeCancel=state().subscriptions;
        await pendingItem(page,'pending').getByRole('button').nth(0).click();await page.locator('.swal2-popup').getByRole('button',{name:'Annulla',exact:true}).click();
        expect(state().subscriptions).toEqual(beforeCancel);await take('dashboard-list-approval-cancelled',card('Iscrizioni da approvare'));
        const beforeDenied=state().subscriptions;
        await pendingItem(reader.page,'pending').getByRole('button').nth(0).click();
        const denied=postFor(`subscription/${f.subscriptions.pending.id}/approve`,reader.page);
        await reader.page.locator('.swal2-popup').getByRole('button',{name:'Approva',exact:true}).click();expect((await denied).status()).toBe(403);
        expect(state().subscriptions).toEqual(beforeDenied);
        report.expected_denials.push({path:`/api/subscription/${f.subscriptions.pending.id}/approve`,method:'POST',status:403,identity:'reader',observed_browser:true});
        await expect(cards(reader.page,'Iscrizioni da approvare').locator(`a[href$="/members/list/detail/${f.subscriptions.pending.id}/info"]`)).toBeVisible();
        await take('dashboard-list-reader-approval-rejected',cards(reader.page,'Iscrizioni da approvare'),reader.page);
        proof('pending_cancel_and_reader_denial_unchanged',true);
        await pendingItem(page,'pending').getByRole('button').nth(0).click();
        await take('dashboard-list-approval-confirmation',page.locator('.swal2-popup'));
        const approve=postFor(`subscription/${f.subscriptions.pending.id}/approve`);
        await page.locator('.swal2-popup').getByRole('button',{name:'Approva',exact:true}).click();expect((await approve).status()).toBe(200);
        await reloadDashboard();expect(state().subscriptions.pending).toBe(4);await expect(pendingItem(page,'pending')).toHaveCount(0);
        await take('dashboard-list-approved-removed',card('Iscrizioni da approvare'));
        await pendingItem(page,'unsigned').getByRole('button').nth(1).click();
        await take('dashboard-list-rejection-confirmation',page.locator('.swal2-popup'));
        const reject=postFor(`subscription/${f.subscriptions.unsigned.id}/reject`);
        await page.locator('.swal2-popup').getByRole('button',{name:'Rifiuta',exact:true}).click();expect((await reject).status()).toBe(200);
        await reloadDashboard();expect(state().subscriptions.unsigned).toBe(3);await expect(card('Iscrizioni da approvare').getByText('Nessun socio da approvare',{exact:true})).toBeVisible();
        await take('dashboard-list-rejected-removed',card('Iscrizioni da approvare'));proof('approve_and_reject_persisted',true);
        const soon=await widget('expiringmedicalcertificates','expiring_medical_certificates');
        expect(soon.map(x=>x.subscription_id)).toEqual(['medical-today','medical-thirty'].map(k=>f.subscriptions[k].id));
        expect(soon.map(x=>x.days_left)).toEqual([0,30]);await take('dashboard-list-medical-zero-thirty',card('Certificati medici in scadenza'));
        const expired=await widget('expiredmedicalcertificates','expired_medical_certificates');
        // Archived registrations are currently included by the expired query, unlike the expiring query.
        expect(expired.map(x=>x.subscription_id)).toEqual(['medical-archived','medical-expired'].map(k=>f.subscriptions[k].id));
        expect(expired.map(x=>x.days_left)).toEqual([-5,-1]);await take('dashboard-list-medical-expired-and-archived',card('Certificati medici scaduti'));
        const medicalId=f.subscriptions['medical-expired'].id;
        await card('Certificati medici scaduti').locator(`a[href$="/members/list/detail/${medicalId}/medical"]`).click();
        await expect(page).toHaveURL(new RegExp('/members/list/detail/'+medicalId+'/medical'));
        const drawer=page.locator('#bkn_content');
        await expect(page.getByText('Informazioni certificato medico',{exact:true})).toBeVisible();
        await expect(page.locator('.card-title').filter({hasText:/Emma/})).toContainText('Ferrari');
        await take('dashboard-list-medical-member-link',drawer);
        await drawer.getByRole('button',{name:'Modifica scadenza',exact:true}).click();
        const dateModal=page.locator('#add-medical-certificate-modal');await expect(dateModal).toBeVisible();
        await dateModal.locator('input[name="expiring_date"]').fill(f.medical['medical-thirty'].expiration);
        await take('dashboard-list-medical-date-editor',dateModal.locator('.modal-content'));
        const saveDate=postFor(`subscription/${medicalId}/medical-certificate/set-certificate-expiration`);
        await dateModal.getByRole('button',{name:'Salva',exact:true}).click();expect((await saveDate).status()).toBe(200);
        await reloadDashboard();expect(state().medical['medical-expired']).toBe(f.medical['medical-thirty'].expiration);
        expect((await widget('expiredmedicalcertificates','expired_medical_certificates')).map(x=>x.subscription_id)).toEqual([f.subscriptions['medical-archived'].id]);
        expect((await widget('expiringmedicalcertificates','expiring_medical_certificates')).map(x=>x.subscription_id)).toContain(medicalId);
        await take('dashboard-list-medical-corrected-after-reload',card('Certificati medici in scadenza'));
        await reloadDashboard(reader.page,reader.api);
        await cards(reader.page,'Certificati medici in scadenza').locator(`a[href$="/members/list/detail/${medicalId}/medical"]`).click();
        await expect(reader.page).toHaveURL(new RegExp('/members/list/detail/'+medicalId+'/medical'));
        const readOnly=reader.page.locator('#bkn_content');
        await expect(reader.page.getByText('Informazioni certificato medico',{exact:true})).toBeVisible();
        await expect(readOnly.getByRole('button',{name:'Modifica scadenza',exact:true})).toHaveCount(0);
        const medicalBefore=state().medical;
        expect((await reader.api(`subscription/${medicalId}/medical-certificate/set-certificate-expiration`,{method:'POST',
            data:{subscription_id:medicalId,certificate_expiring_date:input.reference_date.split('-').reverse().join('/')}})).status()).toBe(403);
        expect(state().medical).toEqual(medicalBefore);await take('dashboard-list-reader-medical-readonly',readOnly,reader.page);
        proof('medical_date_boundaries_and_saved_correction',true);proof('reader_medical_denied_unchanged',true);
        await reloadDashboard();
        const due=await widget('expiredPayments','expired_payments');
        expect(due.map(x=>x.payment_id)).toEqual(['future-seven','today','overdue'].map(k=>f.payments[k].id));
        expect(due.map(x=>x.expired_days)).toEqual([-7,0,29]);
        await expect(card('Pagamenti scaduti e in scadenza')).toContainText('scade oggi');
        await expect(card('Pagamenti scaduti e in scadenza')).toContainText('scade tra 7 gg.');
        await expect(card('Pagamenti scaduti e in scadenza')).toContainText('scaduto da 29 gg.');
        await take('dashboard-list-payment-date-boundaries',card('Pagamenti scaduti e in scadenza'));
        const paymentItem=()=>card('Pagamenti scaduti e in scadenza').locator('.border-right').filter({hasText:'scaduto da 29 gg.'});
        const paymentBefore=state().payments;
        await paymentItem().getByRole('button',{name:'Segna come pagato',exact:true}).click();
        await page.locator('.swal2-popup').getByRole('button',{name:'Annulla',exact:true}).click();expect(state().payments).toEqual(paymentBefore);
        await take('dashboard-list-payment-cancelled',card('Pagamenti scaduti e in scadenza'));
        await paymentItem().getByRole('button',{name:'Segna come pagato',exact:true}).click();
        await page.locator(`#payment_date_${f.payments.overdue.id}`).fill(input.reference_date);
        await take('dashboard-list-payment-collection-confirmation',page.locator('.swal2-popup'));
        const paid=postFor(`payment/${f.payments.overdue.id}/approve`);
        await page.locator('.swal2-popup').getByRole('button',{name:'Incassa',exact:true}).click();expect((await paid).status()).toBe(200);
        await reloadDashboard();const persisted=state().payments.overdue;
        expect(persisted.paid).toBe(true);expect(persisted.payment_date.startsWith(input.reference_date)).toBe(true);
        expect((await widget('expiredPayments','expired_payments')).map(x=>x.payment_id)).not.toContain(f.payments.overdue.id);
        await take('dashboard-list-paid-entry-removed',card('Pagamenti scaduti e in scadenza'));
        await reloadDashboard(reader.page,reader.api);const blocked=cards(reader.page,'Pagamenti scaduti e in scadenza');
        await expect(blocked.getByText('Non hai i permessi.',{exact:true})).toHaveCount(2);
        await expect(blocked.getByRole('button',{name:'Segna come pagato',exact:true})).toHaveCount(0);
        const blockedBefore=state().payments;
        expect((await reader.api(`payment/${f.payments.today.id}/approve`,{method:'POST',data:{payment_date:input.reference_date}})).status()).toBe(403);
        expect(state().payments).toEqual(blockedBefore);await take('dashboard-list-reader-payment-action-hidden',blocked,reader.page);
        proof('payment_window_cancel_and_collection_persisted',true);proof('reader_payment_denied_unchanged',true);
    } finally {
        if(reader&&readerLayout!==undefined)await applyLayout(reader.api,readerLayout);
        await applyLayout(api,originalLayout);
        dashboardListsHarness('cleanup',input);
    }
    const stableRows=(rows,key)=>Object.values(rows).sort((a,b)=>a[key].localeCompare(b[key]));
    expect(stableRows((await read('subscription/list?pagination[perpage]=100')).data,'subscription_id')).toEqual(stableRows(originalSubscriptions,'subscription_id'));
    expect(stableRows((await read('payment/list?pagination[perpage]=100')).data,'payment_id')).toEqual(stableRows(originalPayments,'payment_id'));
    expect((await profile()).user_data.dashboard_layout).toEqual(originalLayout);
    await reloadDashboard();await take('dashboard-list-fixture-layout-restored');proof('owned_fixture_removed_and_layouts_restored',true);
    report[spec.outcome.field]=facts;
    report.checks=['six real widget payloads and visible cards with nonempty boundary fixtures',
        'real attendance, approval/rejection, medical date and collection UI actions persisted after reload',
        'reader controls and real forbidden mutations preserve database state',
        'fictional fixture preparation isolated from UI evidence; owned cleanup and both layouts restored'];
 }});
