"""Prepare a committed release candidate without publishing or rewriting proof.

The original evaluated corpus is validated against its original authoring input.
A separate binding proves that the final manual commit contains those exact
generated bytes. This binding is preparation evidence, not a new browser run.
"""
import copy
from datetime import datetime, timezone
from html.parser import HTMLParser
import json
import os
import re
import shutil
import subprocess
import tempfile
from pathlib import Path
from urllib.parse import quote, urlsplit
from urllib.request import HTTPRedirectHandler, Request, build_opener

from .index import (EvidenceError, ManualIndex, build_index, canonical, digest,
                    file_digest, load_source_catalog, promote, seal_index)


def owned(root, relative):
    root = Path(root).resolve()
    if (not isinstance(relative, str) or not relative or '\\' in relative
            or Path(relative).is_absolute() or '..' in Path(relative).parts
            or any(ord(character) < 32 for character in relative)):
        raise EvidenceError('Invalid release artifact path')
    path = root
    for part in Path(relative).parts:
        path /= part
        if path.is_symlink():
            raise EvidenceError('Release artifacts cannot contain symlinks')
    if path == root or not path.resolve().is_relative_to(root):
        raise EvidenceError('Release artifact escapes its owner')
    return path


def git(root, *arguments):
    try:
        return subprocess.check_output(['git', '-C', str(root), *arguments],
            env={**os.environ, 'GIT_OPTIONAL_LOCKS': '0'}, stderr=subprocess.PIPE)
    except subprocess.CalledProcessError as exc:
        raise EvidenceError('Release input is not the required Git repository/blob') from exc


def committed_checkout(root):
    root = Path(root).resolve()
    if Path(git(root, 'rev-parse', '--show-toplevel').decode().strip()).resolve() != root:
        raise EvidenceError('Release input must be a repository root')
    if git(root, 'status', '--porcelain=v1', '--untracked-files=all').strip():
        raise EvidenceError('Release input checkout must be clean and committed')
    revision = git(root, 'rev-parse', 'HEAD').decode().strip()
    if not re.fullmatch(r'[0-9a-f]{40}', revision):
        raise EvidenceError('Release input must have a committed revision')
    return revision


def verify_blob(root, revision, relative, expected):
    path = owned(root, relative)
    entry = git(root, 'ls-tree', '-z', revision, '--', relative).split(b'\0')
    if (len(entry) != 2 or not entry[0] or b'\t' not in entry[0]
            or entry[0].split(b'\t', 1)[1].decode() != relative
            or entry[0].split(b' ', 1)[0] not in (b'100644', b'100755')):
        raise EvidenceError('Release input is not a regular committed file: ' + relative)
    blob = git(root, 'show', revision + ':' + relative)
    if digest(blob) != expected or file_digest(path) != expected:
        raise EvidenceError('Committed release bytes differ from verified input: ' + relative)
    return blob


def read_json(root, relative):
    return json.loads(owned(root, relative).read_text())


def prepare_release(run_path, application_path, manual_path, output_path, *, release):
    """Atomically stage a prepared package; never modify input runs or commits."""
    run, application, manual, output = (Path(path).resolve() for path in
        (run_path, application_path, manual_path, output_path))
    if output.exists() or any(output == root or output.is_relative_to(root)
            for root in (run, application, manual)):
        raise EvidenceError('Use a new output directory outside the input repositories/run')
    state = read_json(run, 'run.json')
    manifest = read_json(run, 'manifest.json')
    original = ManualIndex.load(owned(run, 'index.json'))
    metadata = original.value['metadata']
    application_revision = committed_checkout(application)
    manual_revision = committed_checkout(manual)
    application_input = state.get('application_input', {})
    if (state.get('status') != 'evaluated' or state.get('run_id') != run.name
            or application_input.get('state') != 'committed' or application_input.get('uncommitted_files')
            or metadata.get('code_state') != 'committed' or metadata.get('uncommitted_code')
            or application_revision != application_input.get('revision')
            or application_revision != metadata.get('application_revision')
            or manifest.get('metadata') != metadata or not release
            or release != metadata.get('release') or release != state.get('release')
            or state.get('manual_input', {}).get('revision') != metadata.get('manual_revision')):
        raise EvidenceError('Preparation requires evaluated evidence for this committed application and release')
    if not metadata.get('source_catalog'):
        raise EvidenceError('Preparation requires a validated complete source catalog')
    generated_manual = owned(run, 'manual')
    catalog = load_source_catalog(generated_manual, application, manifest, run)
    if original.value.get('catalog') != catalog:
        raise EvidenceError('Evaluated index differs from its retained source catalog')
    bindings = dict(original.value['dependencies'])
    bindings.update({path: record['sha256'] for path, record in catalog['files'].items()})
    for chunk in original.value['chunks']:
        bindings.update(chunk.get('runtime_dependencies', {}))
    for relative, expected in bindings.items():
        verify_blob(application, application_revision, relative, expected)
    rebuilt = build_index(generated_manual, application, manifest, artifact_root=run)
    if rebuilt['identity'] != original.value['identity']:
        raise EvidenceError('Evaluated corpus cannot be reproduced from retained proof')
    # A passed report alone is insufficient: bind the evaluation to the corpus,
    # and rendered pages to the exact generated MDX the final commit will serve.
    evaluation = read_json(run, 'evaluation.json')
    embedded = read_json(run, 'embedded-manual.json')
    render = read_json(run, 'render.json')
    if (evaluation.get('status') != 'passed' or evaluation.get('corpus_identity') != original.value['identity']
            or evaluation.get('application_revision') != application_revision or evaluation.get('version') != release
            or embedded.get('status') != 'passed' or embedded.get('backend') != 'real'
            or embedded.get('application_revision') != application_revision or render.get('status') != 'passed'):
        raise EvidenceError('Preparation requires retained successful MCP/agent, reader and render evidence')
    rendered = {page['page']: page for page in render.get('pages', [])}
    verified_pages = {chunk['page'] for chunk in original.value['chunks']}
    if not verified_pages or set(rendered) != verified_pages or len(rendered) != len(render.get('pages', [])):
        raise EvidenceError('Rendering evidence does not cover exactly the verified pages')
    manual_bindings = dict(catalog['manual_files'])
    manual_bindings['.manuale-evidence.json'] = file_digest(owned(generated_manual, '.manuale-evidence.json'))
    for page in verified_pages:
        record = rendered[page]
        chunks = [chunk for chunk in original.value['chunks'] if chunk['page'] == page]
        displayed = {path for chunk in chunks for path in (
            [path for block in chunk['reader'] for path in block.get('screenshots', [])]
            if 'reader' in chunk else [image['path'] for image in chunk['screenshots']])}
        if (record.get('source_sha256') != manual_bindings[page + '.mdx']
                or {chunk['section'] for chunk in chunks} - set(record.get('anchors', []))
                or displayed - set(record.get('images', []))):
            raise EvidenceError('Rendered content differs from the verified manual')
    for chunk in original.value['chunks']:
        for image in chunk['screenshots']:
            manual_bindings[image['path']] = image['sha256']
    manual_bytes = {relative: verify_blob(manual, manual_revision, relative, expected)
                    for relative, expected in manual_bindings.items()}
    origin = metadata.get('canonical_manual_url') or state.get('manual_url', '')
    parsed = urlsplit(origin)
    if (parsed.scheme != 'https' or not parsed.netloc or parsed.username or parsed.password
            or parsed.query or parsed.fragment):
        raise EvidenceError('Preparation requires the configured canonical HTTPS manual URL')
    origin = origin.rstrip('/')
    # Keep the original catalog/reuse hashes in their original verification
    # metadata. The new catalog records only a proven final Git content binding.
    candidate_catalog = copy.deepcopy(catalog)
    candidate_catalog.update(manual_revision=manual_revision,
        authoring_manual_revision=metadata['manual_revision'])
    candidate_catalog_bytes = (canonical(candidate_catalog) + '\n').encode()
    candidate_manifest = copy.deepcopy(manifest)
    candidate_metadata = copy.deepcopy(metadata)
    candidate_metadata.pop('evidence_reuse', None)
    candidate_metadata.update(manual_revision=manual_revision, manual_state='committed',
        code_state='committed', publication_status='prepared', manual_url=origin,
        authoring_manual_revision=metadata['manual_revision'],
        verification={'corpus_identity': original.value['identity'], 'metadata': copy.deepcopy(metadata),
            'manifest_path': 'evidence/manifest.json', 'index_path': 'evidence/index.json',
            'evidence_kind': state.get('evidence_kind', 'retained-evaluated-run')},
        source_catalog={'format': 1, 'path': 'source-catalog.json', 'sha256': digest(candidate_catalog_bytes)})
    candidate_manifest['metadata'] = candidate_metadata
    candidate = copy.deepcopy(original.value)
    candidate.update(metadata=candidate_metadata, catalog=candidate_catalog)
    for chunk in candidate['chunks']:
        chunk['url'] = origin + '/' + quote(chunk['page']) + '#' + quote(chunk.get('citation_anchor', chunk['section']), safe='')
        for image in chunk['screenshots']:
            image['url'] = origin + '/' + quote(image['path'])
    candidate = seal_index(candidate)
    # This catches accidental catalog/hash rebinding before any package exists.
    candidate_catalog_binding = digest(candidate_catalog_bytes)
    proof_paths = {'run.json', 'manifest.json', 'index.json', 'evaluation.json', 'render.json', 'embedded-manual.json',
                   metadata['source_catalog']['path']}
    proof_paths.update(scenario['report_path'] for scenario in manifest.get('scenarios', []))
    if metadata.get('evidence_reuse'):
        proof_paths.add(metadata['evidence_reuse']['path'])
    for directory in ('captures', 'masters', 'evidence-origin'):
        source = owned(run, directory)
        if source.exists():
            proof_paths.update(str(path.relative_to(run)) for path in source.rglob('*') if path.is_file()
                and (path.name.endswith('.manifest.json') if directory == 'evidence-origin' else path.suffix.lower() == '.png'))
    proof_bytes = {relative: owned(run, relative).read_bytes() for relative in sorted(proof_paths)}
    plan = {'format': 1, 'status': 'prepared', 'published': False,
        'evidence_kind': state.get('evidence_kind', 'retained-evaluated-run'),
        'application_revision': application_revision, 'manual_revision': manual_revision, 'release': release,
        'authoring_manual_revision': metadata['manual_revision'], 'verified_corpus_identity': original.value['identity'],
        'candidate_corpus_identity': candidate['identity'], 'canonical_manual_url': origin,
        'candidate_catalog_sha256': candidate_catalog_binding, 'manual_file_hashes': manual_bindings,
        'retained_evidence': {relative: digest(contents) for relative, contents in proof_bytes.items()},
        'gaps': copy.deepcopy(original.value['gaps']),
        'next_steps': ['Review the prepared candidate and explicit coverage gaps.',
            'Publish the exact committed manual and retained evidence through the existing configured deployment.',
            'Verify deployed pages, anchors, image bytes and evidence availability against this plan.',
            'Only after that verification may a separate authorized publication step mark the corpus published.',
            'Promote the published corpus under APPLICATION_REVISION/RELEASE.json; production synchronization rejects this prepared candidate.'],
        'external_publication_verified': False}
    # Input contents are read and validated before creating the new output.
    output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(dir=output.parent, prefix='.manual-release-') as temporary:
        stage = Path(temporary) / 'package'
        stage.mkdir()
        for relative, contents in proof_bytes.items():
            target = owned(stage / 'evidence', relative)
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(contents)
        for relative, contents in manual_bytes.items():
            target = owned(stage / 'manual', relative)
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(contents)
        owned(stage, 'source-catalog.json').write_bytes(candidate_catalog_bytes)
        if build_index(manual, application, manifest, artifact_root=stage / 'evidence')['identity'] != original.value['identity']:
            raise EvidenceError('Retained proof changed while staging the release')
        load_source_catalog(manual, application, candidate_manifest, stage)
        promote(candidate_manifest, stage / 'manifest.json')
        promote(candidate, stage / 'index.json')
        promote(plan, stage / 'publication-plan.json')
        # The original verification index and report bytes remain untouched.
        if committed_checkout(application) != application_revision or committed_checkout(manual) != manual_revision:
            raise EvidenceError('Release input checkout changed during preparation')
        for relative, expected in manual_bindings.items():
            verify_blob(manual, manual_revision, relative, expected)
        stage.rename(output)
    return plan


def validate_prepared_package(prepared_path, application_path, manual_path, *, release):
    """Reproduce preparation from retained proof rather than trusting labels."""
    prepared = Path(prepared_path).resolve()
    core_bytes = {relative: owned(prepared, relative).read_bytes()
        for relative in ('index.json', 'manifest.json', 'source-catalog.json', 'publication-plan.json')}
    plan = json.loads(core_bytes['publication-plan.json'])
    if plan.get('status') != 'prepared' or plan.get('published') is not False or plan.get('release') != release:
        raise EvidenceError('Availability verification requires the prepared target release')
    state = read_json(prepared, 'evidence/run.json')
    with tempfile.TemporaryDirectory(prefix='manual-publication-validation-') as temporary:
        root = Path(temporary)
        run = owned(root, state['run_id'])
        for folder, bindings, destination in [('evidence', plan['retained_evidence'], run),
                ('manual', plan['manual_file_hashes'], run / 'manual')]:
            for relative, expected in bindings.items():
                contents = owned(prepared / folder, relative).read_bytes()
                if digest(contents) != expected:
                    raise EvidenceError('Prepared package bytes changed: ' + folder + '/' + relative)
                target = owned(destination, relative)
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes(contents)
        rebuilt = root / 'rebuilt'
        prepare_release(run, application_path, manual_path, rebuilt, release=release)
        for relative in ('index.json', 'manifest.json', 'source-catalog.json', 'publication-plan.json'):
            if core_bytes[relative] != owned(rebuilt, relative).read_bytes():
                raise EvidenceError('Prepared package differs from its validated derivation: ' + relative)
    candidate = ManualIndex(json.loads(core_bytes['index.json']))
    candidate.prepared_manifest = json.loads(core_bytes['manifest.json'])
    candidate.prepared_catalog_bytes = core_bytes['source-catalog.json']
    return candidate, plan


def https_url(value):
    parsed = urlsplit(value)
    if (parsed.scheme != 'https' or not parsed.netloc or parsed.username or parsed.password
            or parsed.fragment or any(ord(character) < 33 for character in value)):
        raise EvidenceError('Availability sources must be configured credential-free HTTPS URLs')
    return value


class _SameOriginHTTPSRedirect(HTTPRedirectHandler):
    def redirect_request(self, request, response, code, message, headers, newurl):
        https_url(newurl)
        if urlsplit(newurl).netloc != urlsplit(request.full_url).netloc:
            raise EvidenceError('Availability checks cannot follow cross-origin redirects')
        return super().redirect_request(request, response, code, message, headers, newurl)


def read_https(url, *, require_html=False):
    """Read public bytes only; no credentials, HTTP downgrade or opaque redirect."""
    https_url(url)
    request = Request(url, headers={'User-Agent': 'Assozeta-manuale-availability', 'Cache-Control': 'no-cache'})
    with build_opener(_SameOriginHTTPSRedirect()).open(request, timeout=15) as response:
        https_url(response.geturl())
        if response.status != 200 or urlsplit(response.geturl()).netloc != urlsplit(url).netloc:
            raise EvidenceError('Availability source did not return the requested public resource')
        if require_html and response.headers.get_content_type() not in ('text/html', 'application/xhtml+xml'):
            raise EvidenceError('Canonical manual page is not served as HTML')
        contents = response.read(64 * 1024 * 1024 + 1)
        if len(contents) > 64 * 1024 * 1024:
            raise EvidenceError('Availability resource exceeds its size limit')
        return contents


class _VisiblePage(HTMLParser):
    """Ignore scripts and hidden markup; retain section positions and prose."""
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.tokens, self.ids, self.stack = [], {}, []

    def handle_starttag(self, tag, attributes):
        attrs = dict(attributes)
        hidden = (bool(self.stack and self.stack[-1][1]) or tag in ('script', 'style', 'template', 'head')
            or 'hidden' in attrs or attrs.get('aria-hidden') == 'true'
            or 'display:none' in attrs.get('style', '').replace(' ', '').lower())
        if not hidden:
            if attrs.get('id'):
                if attrs['id'] in self.ids:
                    raise EvidenceError('Deployed page has duplicate section identities')
                self.ids[attrs['id']] = len(self.tokens)
            if tag == 'img':
                self.tokens.extend(_words(attrs.get('alt', '')))
        if tag not in ('area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input', 'link', 'meta', 'param', 'source', 'track', 'wbr'):
            self.stack.append((tag, hidden))

    def handle_endtag(self, tag):
        for position in range(len(self.stack) - 1, -1, -1):
            if self.stack[position][0] == tag:
                del self.stack[position:]
                return

    def handle_data(self, text):
        if not self.stack or not self.stack[-1][1]:
            self.tokens.extend(_words(text))


def _words(text):
    return re.findall(r'[a-zà-ÿ0-9]+', text.casefold())


def verify_page_prose(contents, chunks, catalog_page):
    parsed = _VisiblePage()
    parsed.feed(contents.decode('utf-8'))
    boundaries = {entry['id'] for entry in catalog_page['sections']}
    boundaries.update(chunk.get('citation_anchor', chunk['section']) for chunk in chunks)
    for chunk in chunks:
        anchor = chunk.get('citation_anchor', chunk['section'])
        if anchor not in parsed.ids:
            raise EvidenceError('Deployed page is missing verified section: ' + chunk['id'])
        start = parsed.ids[anchor]
        end = min([parsed.ids[key] for key in boundaries if key in parsed.ids and parsed.ids[key] > start]
                  or [len(parsed.tokens)])
        observed = iter(parsed.tokens[start:end])
        # All verified prose must occur in order inside its section, allowing
        # renderer-added step numbers. Script/source JSON text is never proof.
        expected = _words(chunk['text'])
        if not expected or any(not any(word == token for word in observed) for token in expected):
            raise EvidenceError('Deployed visible prose differs from verified section: ' + chunk['id'])


def verify_release_availability(prepared_path, application_path, manual_path, output_path, *, release,
                                evidence_base, deployment_environment=None):
    """Read deployed resources and stage local promotion output only.

    Mintlify's repo README describes automatic deployment, but supplies no
    commit attestation. A matching latest successful GitHub Deployment for the
    configured environment is required in addition to all content checks.
    Without that authoritative record, retain prepared status and report the
    missing proof. This command never pushes or deploys anything.
    """
    prepared, output = Path(prepared_path).resolve(), Path(output_path).resolve()
    if output.exists() or any(output == Path(root).resolve() or output.is_relative_to(Path(root).resolve())
            for root in (prepared, application_path, manual_path)):
        raise EvidenceError('Use a new availability output outside input repositories/package')
    candidate, plan = validate_prepared_package(prepared, application_path, manual_path, release=release)
    https_url(evidence_base)
    if urlsplit(evidence_base).query:
        raise EvidenceError('Public evidence base cannot contain a query')
    report = {'format': 1, 'status': 'checking', 'checked_at': datetime.now(timezone.utc).isoformat(),
        'evidence_kind': plan.get('evidence_kind', 'retained-evaluated-run'),
        'candidate_corpus_identity': candidate.value['identity'], 'application_revision': plan['application_revision'],
        'manual_revision': plan['manual_revision'], 'release': release, 'resources': [], 'missing_proof': [],
        'content_availability': 'not_verified', 'deployment_revision': 'unattested',
        'external_actions': [], 'limits': 'HTTP visible-prose/anchor and byte checks; not browser rendering, visual QA or absence of extra unverified prose.'}

    def check(url, expected=None, *, html=False):
        contents = read_https(url, require_html=html)
        actual = digest(contents)
        if expected is not None and actual != expected:
            raise EvidenceError('Published bytes differ from the prepared binding: ' + url)
        report['resources'].append({'url': url, 'sha256': actual, 'bytes': len(contents)})
        return contents

    def github_records(url):
        records = []
        for page in range(1, 11):
            query = url + '?per_page=100' + ('&page=' + str(page) if page > 1 else '')
            batch = json.loads(check(query))
            if not isinstance(batch, list) or len(batch) > 100 or any(not isinstance(item, dict) for item in batch):
                raise EvidenceError('Invalid public deployment records')
            records.extend(batch)
            if len(batch) < 100:
                return records
        raise EvidenceError('Public deployment history exceeds the bounded availability check')

    def most_recent(records):
        # Select by the API's explicit creation times, never by response order.
        def key(record):
            timestamp = datetime.fromisoformat(record['created_at'])
            identifier = record['id']
            if timestamp.tzinfo is None or type(identifier) is not int or identifier <= 0:
                raise EvidenceError('Invalid authoritative deployment record identity/time')
            return timestamp, identifier
        return max(records, key=key)

    try:
        # The inspected source is Bakney/manuale, not a mutable branch label.
        source = 'https://raw.githubusercontent.com/Bakney/manuale/' + plan['manual_revision']
        for relative, expected in sorted(plan['manual_file_hashes'].items()):
            check(source + '/' + quote(relative), expected)
        origin = plan['canonical_manual_url'].rstrip('/')
        for page in sorted({chunk['page'] for chunk in candidate.value['chunks']}):
            chunks = [chunk for chunk in candidate.value['chunks'] if chunk['page'] == page]
            catalog_page = next(entry for entry in candidate.value['catalog']['pages'] if entry['path'] == page + '.mdx')
            verify_page_prose(check(origin + '/' + quote(page), html=True), chunks, catalog_page)
        images = {image['path']: image['sha256'] for chunk in candidate.value['chunks'] for image in chunk['screenshots']}
        for relative, expected in sorted(images.items()):
            check(origin + '/' + quote(relative), expected)
        for relative, expected in sorted(plan['retained_evidence'].items()):
            check(evidence_base.rstrip('/') + '/' + quote(relative), expected)
        report['content_availability'] = 'verified'
        if not deployment_environment:
            report['missing_proof'].append('Configure the actual deployment environment and expose its successful deployment-to-commit record; Mintlify auto-deploy prose is insufficient.')
        else:
            api = 'https://api.github.com/repos/Bakney/manuale/deployments'
            deployments = github_records(api)
            matching = [item for item in deployments if item.get('environment') == deployment_environment]
            if not matching:
                report['missing_proof'].append('No authoritative GitHub Deployment is available for the configured Mintlify environment; provide the actual deployed-commit proof integration.')
            else:
                latest = most_recent(matching)
                identifier = latest['id']
                if type(identifier) is not int or identifier <= 0:
                    raise EvidenceError('Invalid authoritative deployment identity')
                statuses = github_records('https://api.github.com/repos/Bakney/manuale/deployments/' + str(identifier) + '/statuses')
                current_status = most_recent(statuses) if statuses else {}
                if (latest.get('sha') != plan['manual_revision'] or not statuses
                        or current_status.get('state') != 'success'
                        or current_status.get('environment_url', '').rstrip('/') != origin):
                    report['missing_proof'].append('The latest configured-environment deployment is not a successful deployment of the exact final manual commit at the canonical site.')
                else:
                    report['deployment'] = {'id': identifier, 'environment': deployment_environment,
                        'manual_revision': latest['sha'], 'site': origin, 'status_id': current_status.get('id')}
                    report['deployment_revision'] = 'verified'
        report['status'] = 'publication-blocked' if report['missing_proof'] else 'availability-verified'
    except (OSError, ValueError, KeyError, TypeError) as exc:
        if report['content_availability'] == 'verified' and report['deployment_revision'] == 'unattested':
            report['missing_proof'].append('Authoritative exact deployment revision could not be verified: ' + str(exc))
            report['status'] = 'publication-blocked'
        else:
            report.update(status='availability-failed', error=str(exc))
    output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(dir=output.parent, prefix='.manual-availability-') as temporary:
        stage = Path(temporary) / 'result'
        stage.mkdir()
        report_bytes = (canonical(report) + '\n').encode()
        (stage / 'availability-report.json').write_bytes(report_bytes)
        if report['status'] == 'availability-verified':
            published = copy.deepcopy(candidate.value)
            published['metadata'].update(publication_status='published',
                publication_availability={'path': 'availability-report.json', 'sha256': digest(report_bytes),
                    'prepared_corpus_identity': candidate.value['identity']})
            published['metadata']['verification'].update(
                public_manifest_url=evidence_base.rstrip('/') + '/manifest.json',
                public_index_url=evidence_base.rstrip('/') + '/index.json')
            published = seal_index(published)
            promote(published, stage / 'index.json')
            final_manifest = copy.deepcopy(candidate.prepared_manifest)
            final_manifest['metadata'] = published['metadata']
            promote(final_manifest, stage / 'manifest.json')
            (stage / 'source-catalog.json').write_bytes(candidate.prepared_catalog_bytes)
            promote({'status': 'local-promotion-output', 'external_actions': [],
                'corpus_identity': published['identity'], 'availability_sha256': digest(report_bytes),
                'release_path': plan['application_revision'] + '/' + quote(release, safe='') + '.json'}, stage / 'promotion-plan.json')
        stage.rename(output)
    return report
