[pytest]
DJANGO_SETTINGS_MODULE = core.settings
python_files = test_*.py
testpaths =
    application
    instance
    communications
    notifications
    core
    docmanager
addopts =
    --strict-markers
    --tb=short
    --timeout=300
