# Generated by Django 4.2.4 on 2023-09-03 09:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0096_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationConfiguration',
            fields=[
                ('communication_configuration_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email_smtp_host', models.CharField(blank=True, max_length=255, null=True)),
                ('email_smtp_port', models.PositiveIntegerField(blank=True, null=True)),
                ('email_smtp_user', models.CharField(blank=True, max_length=255, null=True)),
                ('email_smtp_password', models.CharField(blank=True, max_length=255, null=True)),
                ('email_sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email_encryption', models.CharField(choices=[('SSL', 'SSL'), ('TLS', 'STARTTLS'), ('NONE', 'No Encryption')], default='NONE', help_text='Choose the encryption method for the SMTP connection.', max_length=10)),
                ('daily_email_limit', models.PositiveIntegerField(default=1000)),
                ('sms_balance', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('INSIDE_APP', 'Inside App Message')], max_length=50)),
                ('content', models.TextField()),
                ('sport_association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.sportassociation')),
            ],
        ),
        migrations.CreateModel(
            name='SmsCreditPayment',
            fields=[
                ('sms_credit_payment_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sport_association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.sportassociation')),
            ],
        ),
        migrations.CreateModel(
            name='MessageTransaction',
            fields=[
                ('message_transaction_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('recipient', models.CharField(max_length=255)),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
                ('delivered_on', models.DateTimeField(blank=True, null=True)),
                ('opened_on', models.DateTimeField(blank=True, null=True)),
                ('clicked_on', models.DateTimeField(blank=True, null=True)),
                ('bounced_on', models.DateTimeField(blank=True, null=True)),
                ('bounced_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('bounced_type', models.CharField(blank=True, max_length=255, null=True)),
                ('bounced_status', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communications.message')),
            ],
        ),
    ]
