# Generated by Django 4.2.4 on 2023-09-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationconfiguration',
            name='daily_email_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
