# Generated by Django 4.2.4 on 2023-09-03 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0096_alter_user_role'),
        ('communications', '0002_communicationconfiguration_daily_email_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationconfiguration',
            name='sport_association',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.sportassociation'),
        ),
    ]
