# Generated by Django 4.2.4 on 2023-09-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_communicationconfiguration_sport_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscreditpayment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
