# Generated by Django 4.2.4 on 2023-09-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_smscreditpayment_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
