# Generated by Django 4.2.4 on 2023-09-04 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_message_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message',
        ),
    ]
