# Generated by Django 4.2.4 on 2023-09-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0007_rename_content_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationconfiguration',
            name='sms_balance',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
