# Generated by Django 4.2.4 on 2023-10-07 08:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0104_user_tables_settings'),
        ('communications', '0008_alter_communicationconfiguration_sms_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationWorkflow',
            fields=[
                ('automation_workflow_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('automation_tree', models.JSONField(default=list)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('sport_association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.sportassociation')),
            ],
        ),
    ]
