# Generated by Django 4.2.4 on 2024-01-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0009_automationworkflow'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='automationworkflow',
            index=models.Index(fields=['automation_workflow_id', 'sport_association'], name='communicati_automat_e17cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationconfiguration',
            index=models.Index(fields=['communication_configuration_id', 'sport_association'], name='communicati_communi_0487aa_idx'),
        ),
        migrations.AddIndex(
            model_name='messagetransaction',
            index=models.Index(fields=['message_transaction_id', 'message'], name='communicati_message_3ccfe1_idx'),
        ),
    ]
