# Generated by Django 5.2.1 on 2026-09-20 19:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0429_repair_group_sport_association_fk'),
        ('communications', '0011_remove_legacy_message_channels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffBoardMessage',
            fields=[
                ('staff_board_message_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sport_association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.sportassociation')),
            ],
            options={
                'ordering': ['-pinned', '-created_at'],
                'indexes': [models.Index(fields=['sport_association', 'pinned', 'created_at'], name='communicati_sport_a_125a4d_idx')],
            },
        ),
    ]
